global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['localhost:9090']

  - job_name: app
    scrape_interval: 5s
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: [ 'api:8080' ]