---
apiVersion: v1
kind: Service
metadata:
  name: api-application
  labels:
    app: api-application
spec:
  ports:
    - port: 8080
      targetPort: application
      protocol: TCP
      name: http
    - port: 9091
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: api-application
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-application
  labels:
    app: api-application
spec:
  replicas: 2
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: api-application
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: api-application
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - api-application
              topologyKey: kubernetes.io/hostname
      containers:
        - name: api-application
          image: api-application:latest
          imagePullPolicy: "IfNotPresent"
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: postgresdb
            - name: DB_SCHEMA
              value: public
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: psltest
          ports:
            - name: application
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: application
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 15
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path:  /actuator/health
              port: application
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 10
            successThreshold: 2
            failureThreshold: 10
          resources:
            limits:
              cpu: 800m
              memory: 800Mi
            requests:
              cpu: 400m
              memory: 600Mi