spring:
  application:
    name: "api"
  r2dbc:
    url: "r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:agreement}?currentSchema=${DB_SCHEMA:public}"
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123}
  datasource:
    hikari:
      maximum-pool-size: 10

grpc:
  port: 9091
  enable-reflection: true

management:
  endpoint:
    health:
      enabled: true
      roles: ACTUATOR
      show-details: ALWAYS
      probes:
        enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
    caches:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - loggers
          - caches
  health:
    db:
      enabled: true
    diskspace:
      enabled: false
    group:
      readiness:
        include: '*'
      liveness:
        include: '*'