spring:
  application:
    name: "api"
  datasource:
    hikari:
      maximum-pool-size: 10
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}?currentSchema=${DB_SCHEMA}"

grpc:
  port: 9091
  enable-reflection: true

management:
  endpoint:
    health:
      enabled: true
      roles: ACTUATOR
      show-details: ALWAYS
      probes:
        enabled: true
    info:
      enabled: true
    loggers:
      enabled: true
    prometheus:
      enabled: true
    caches:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
          - prometheus
          - loggers
          - caches
  health:
    db:
      enabled: true
    diskspace:
      enabled: false
    group:
      readiness:
        include: '*'
      liveness:
        include: '*'